### PR TITLE
Support paths as keys to access nested keys

### PR DESCRIPTION
**Pull request by Pafgz**

### CODE REVIEW

**Comment by s4cha** [comment]
@Pafgz I simplified the `invoke` & `compare` functions so that the parsing is shared, cleaning a lot of the code :)

**Comment by s4cha** [comment]
Also the key path parsing is simplified with the following logic (using a loop over recursion)
```kotlin
val keys = key.split(".")
val lastKey = keys.last()
val allKeysButLast = keys.dropLast(1)
var nestedJSON = json
allKeysButLast.forEach { k ->
  if (!nestedJSON.jsonObject.has(k)) {
     return null
  }
  nestedJSON = JSON(nestedJSON.jsonObject.getJSONObject(k))
}
return getSingleValue(nestedJSON, lastKey)
```
Essentially digging to the last key and using the common parsing for the last node :)

**Review by Pafgz — COMMENTED** [review]
I like it a lot! Wünderschön!

**Comment by s4cha** [comment]
Glad you like it ! Let's merge then!

**Pull request merged**
